# Generated by Django 3.2 on 2021-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='features',
            field=models.JSONField(null=True),
        ),
    ]
