# Generated by Django 3.2 on 2021-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stats',
            field=models.JSONField(null=True),
        ),
    ]
