# Generated by Django 3.2 on 2021-05-18 12:14

from django.conf import settings
import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examwording',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(django.contrib.auth.get_user_model), related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examwording',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(django.contrib.auth.get_user_model), related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
