# Generated by Django 3.2 on 2021-07-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_examreport_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReportToApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.examreport')),
            ],
        ),
    ]
