# Generated by Django 3.2 on 2021-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210518_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examwording',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='examwording',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
